from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING, Protocol, runtime_checkable

from visus.web.engine import Engine

if TYPE_CHECKING:
    from visus.web.api.fields import Field


@runtime_checkable
class PageDelegate(Protocol):
    def goto(self, url: str, *, wait_until: str, timeout_ms: int) -> None: ...
    def current_url(self) -> str: ...
    def title(self) -> str: ...
    def content(self) -> str: ...
    def reload(self, *, timeout_ms: int) -> None: ...
    def go_back(self, *, timeout_ms: int) -> None: ...
    def go_forward(self, *, timeout_ms: int) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def handle(self) -> str: ...
    def bring_to_front(self) -> None: ...
    def context(self) -> ContextDelegate: ...
    def locator_count(self, selector: str) -> int: ...
    def locator_is_visible(self, selector: str) -> bool: ...
    def locator_text_content(self, selector: str) -> str | None: ...
    def locator_click(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_fill(self, selector: str, value: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_hover(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_dblclick(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_set_checked(
        self, selector: str, checked: bool, *, timeout_ms: int, force: bool
    ) -> None: ...
    def locator_select_option(
        self,
        selector: str,
        *,
        value: str | None,
        label: str | None,
        index: int | None,
        timeout_ms: int,
    ) -> None: ...
    def locator_press(self, selector: str, key: str, *, timeout_ms: int) -> None: ...
    def locator_press_sequentially(
        self, selector: str, text: str, *, delay_ms: int, timeout_ms: int
    ) -> None: ...
    def locator_focus(self, selector: str, *, timeout_ms: int) -> None: ...
    def locator_blur(self, selector: str, *, timeout_ms: int) -> None: ...
    def locator_clear(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_drag_to(self, selector: str, target: str, *, timeout_ms: int) -> None: ...
    def locator_input_value(self, selector: str) -> str: ...
    def locator_state(self, selector: str, state: str) -> bool: ...
    def locator_all_text(self, selector: str) -> list[str]: ...
    def locator_get_attribute(self, selector: str, name: str) -> str | None: ...
    def expect_poll(
        self,
        selector: str,
        matcher: str,
        arg: dict[str, object] | None,
        *,
        is_not: bool,
        timeout_ms: int,
    ) -> None: ...
    def evaluate(self, expression: str, arg: object) -> object: ...
    def locator_evaluate(self, selector: str, expression: str, arg: object) -> object: ...
    def screenshot(self, *, full_page: bool) -> bytes: ...
    def locator_screenshot(self, selector: str) -> bytes: ...
    def locator_set_input_files(self, selector: str, paths: list[str]) -> None: ...
    def snapshot_handles(self) -> list[str]: ...
    def adopt_new_handle(self, before: list[str], *, timeout_ms: int) -> PageDelegate: ...
    def handle_next_dialog(
        self, *, accept: bool, prompt_text: str | None, timeout_ms: int
    ) -> tuple[str, str]: ...
    def snapshot(self) -> list[dict]: ...  # type: ignore[type-arg]
    def list_fields(
        self, *, kinds: list[str] | None, include_hidden: bool, highlight: bool
    ) -> list[Field]: ...
    def clear_highlights(self) -> None: ...
    def pdf(self) -> bytes: ...
    def snapshot_download_dir(self) -> list[str]: ...
    def wait_for_download(self, before: list[str], *, timeout_ms: int) -> tuple[str, str]: ...
    # --- low-level input devices ---
    def mouse_move(self, x: float, y: float) -> None: ...
    def mouse_down(self) -> None: ...
    def mouse_up(self) -> None: ...
    def mouse_click(self, x: float, y: float) -> None: ...
    def mouse_dblclick(self, x: float, y: float) -> None: ...
    def mouse_wheel(self, delta_x: float, delta_y: float) -> None: ...
    def keyboard_down(self, key: str) -> None: ...
    def keyboard_up(self, key: str) -> None: ...
    def keyboard_press(self, key: str) -> None: ...
    def keyboard_type(self, text: str) -> None: ...
    def keyboard_insert_text(self, text: str) -> None: ...
    # --- network controls (Chromium CDP) ---
    def block_urls(self, patterns: list[str]) -> None: ...
    def set_extra_http_headers(self, headers: dict[str, str]) -> None: ...
    def set_offline(self, offline: bool) -> None: ...
    # --- network/console capture (Chromium logs) ---
    def network_requests(self) -> list[dict[str, object]]: ...
    def console_messages(self) -> list[dict[str, object]]: ...
    def network_marker(self) -> int: ...
    def wait_for_response(
        self, url_pattern: str, *, timeout_ms: int, from_index: int | None = None
    ) -> dict[str, object]: ...
    def response_body(self, request_id: str) -> str: ...
    # --- init scripts + emulation ---
    def add_init_script(self, script: str) -> None: ...
    def set_geolocation(
        self, latitude: float, longitude: float, *, accuracy: float = 100
    ) -> None: ...
    def grant_permissions(self, permissions: list[str], *, origin: str | None = None) -> None: ...
    def set_device_metrics(
        self, width: int, height: int, *, device_scale_factor: float = 1.0, mobile: bool = False
    ) -> None: ...
    def set_viewport_size(self, width: int, height: int) -> None: ...
    # --- observability ---
    def capture_annotated_screenshot(self, selector: str | None) -> bytes: ...
    def step_meta(self, selector: str | None) -> dict[str, object]: ...


@runtime_checkable
class ContextDelegate(Protocol):
    def new_page(self) -> PageDelegate: ...
    def pages(self) -> list[PageDelegate]: ...
    def adopt_open_windows(self) -> list[PageDelegate]: ...
    def close(self) -> None: ...
    def cookies(self) -> list[dict]: ...  # type: ignore[type-arg]
    def add_cookies(self, cookies: list[dict]) -> None: ...  # type: ignore[type-arg]
    def clear_cookies(self) -> None: ...
    def storage_state(self) -> dict: ...  # type: ignore[type-arg]
    def restore_storage_state(self, state: dict) -> None: ...  # type: ignore[type-arg]


@runtime_checkable
class BrowserDelegate(Protocol):
    def new_context(self) -> ContextDelegate: ...
    def contexts(self) -> list[ContextDelegate]: ...
    def dispose(self) -> None: ...


@dataclass(frozen=True)
class BrowserConfig:
    engine: Engine
    options_factory: Callable[..., object]
    service_factory: Callable[..., object]
    driver_factory: Callable[..., object]


@runtime_checkable
class Backend(Protocol):
    def launch(
        self,
        config: BrowserConfig,
        *,
        headless: bool,
        user_data_dir: str | None = None,
        remote_url: str | None = None,
    ) -> BrowserDelegate: ...
