from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

from visus.web.engine import Engine


@runtime_checkable
class PageDelegate(Protocol):
    def goto(self, url: str, *, wait_until: str, timeout_ms: int) -> None: ...
    def current_url(self) -> str: ...
    def title(self) -> str: ...
    def content(self) -> str: ...
    def reload(self, *, timeout_ms: int) -> None: ...
    def go_back(self, *, timeout_ms: int) -> None: ...
    def go_forward(self, *, timeout_ms: int) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def locator_count(self, selector: str) -> int: ...
    def locator_is_visible(self, selector: str) -> bool: ...
    def locator_text_content(self, selector: str) -> str | None: ...
    def locator_click(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_fill(self, selector: str, value: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_hover(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_dblclick(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_set_checked(self, selector: str, checked: bool, *, timeout_ms: int, force: bool) -> None: ...
    def locator_select_option(self, selector: str, *, value: str | None, label: str | None, index: int | None, timeout_ms: int) -> None: ...
    def locator_press(self, selector: str, key: str, *, timeout_ms: int) -> None: ...
    def locator_focus(self, selector: str, *, timeout_ms: int) -> None: ...
    def locator_blur(self, selector: str, *, timeout_ms: int) -> None: ...
    def locator_clear(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_drag_to(self, selector: str, target: str, *, timeout_ms: int) -> None: ...
    def locator_input_value(self, selector: str) -> str: ...
    def locator_state(self, selector: str, state: str) -> bool: ...
    def locator_all_text(self, selector: str) -> list[str]: ...
    def locator_get_attribute(self, selector: str, name: str) -> str | None: ...
    def expect_poll(
        self,
        selector: str,
        matcher: str,
        arg: dict[str, object] | None,
        *,
        is_not: bool,
        timeout_ms: int,
    ) -> None: ...


@runtime_checkable
class ContextDelegate(Protocol):
    def new_page(self) -> PageDelegate: ...
    def pages(self) -> list[PageDelegate]: ...
    def close(self) -> None: ...


@runtime_checkable
class BrowserDelegate(Protocol):
    def new_context(self) -> ContextDelegate: ...
    def contexts(self) -> list[ContextDelegate]: ...
    def dispose(self) -> None: ...


@dataclass(frozen=True)
class BrowserConfig:
    engine: Engine
    options_factory: Callable[..., object]
    service_factory: Callable[..., object]
    driver_factory: Callable[..., object]


@runtime_checkable
class Backend(Protocol):
    def launch(self, config: BrowserConfig, *, headless: bool) -> BrowserDelegate: ...
