from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

from visus.web.engine import Engine


@runtime_checkable
class PageDelegate(Protocol):
    def goto(self, url: str, *, wait_until: str, timeout_ms: int) -> None: ...
    def current_url(self) -> str: ...
    def title(self) -> str: ...
    def content(self) -> str: ...
    def reload(self, *, timeout_ms: int) -> None: ...
    def go_back(self, *, timeout_ms: int) -> None: ...
    def go_forward(self, *, timeout_ms: int) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def locator_count(self, selector: str) -> int: ...
    def locator_is_visible(self, selector: str) -> bool: ...
    def locator_text_content(self, selector: str) -> str | None: ...
    def locator_click(self, selector: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_fill(self, selector: str, value: str, *, timeout_ms: int, force: bool) -> None: ...
    def locator_input_value(self, selector: str) -> str: ...


@runtime_checkable
class ContextDelegate(Protocol):
    def new_page(self) -> PageDelegate: ...
    def pages(self) -> list[PageDelegate]: ...
    def close(self) -> None: ...


@runtime_checkable
class BrowserDelegate(Protocol):
    def new_context(self) -> ContextDelegate: ...
    def contexts(self) -> list[ContextDelegate]: ...
    def dispose(self) -> None: ...


@dataclass(frozen=True)
class BrowserConfig:
    engine: Engine
    options_factory: Callable[..., object]
    service_factory: Callable[..., object]
    driver_factory: Callable[..., object]


@runtime_checkable
class Backend(Protocol):
    def launch(self, config: BrowserConfig, *, headless: bool) -> BrowserDelegate: ...
